{
  "Uuid": "1855764f-2a72-4b27-8738-d4a6d63d7598",
  "IsCustomNode": false,
  "Description": null,
  "Name": "ExtendedTo 3D View",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import sys\r\nimport clr\r\nimport math\r\nimport System\r\nfrom System import Array\r\nfrom System.Collections.Generic import *\r\n\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript.Geometry import *\r\n\r\nclr.AddReference(\"RevitAPIUI\")\r\nimport Autodesk \r\nfrom Autodesk.Revit.UI import *\r\n\r\nimport os.path\r\n\r\nclr.AddReference(\"RevitServices\")\r\nimport RevitServices\t\t\r\nfrom RevitServices.Persistence import DocumentManager \r\nfrom RevitServices.Transactions import TransactionManager \r\n\r\nclr.AddReference(\"RevitAPI\")\r\nimport Autodesk \r\nfrom Autodesk.Revit.DB import *\r\n\r\nfrom System.Collections.Generic import List\r\n\r\nclr.AddReference('System.Drawing')\r\nclr.AddReference('System.Windows.Forms')\r\nimport System.Drawing\r\nimport System.Windows.Forms\r\n\r\nfrom System.Drawing import *\r\nfrom System.Reflection import Assembly\r\nfrom System.Windows.Forms import *\r\n\r\nclr.AddReference('System.Data')\r\nfrom System.Data import *\r\n\r\nclr.AddReference(\"System.Core\")\r\nimport System.Linq\r\nclr.ImportExtensions(System.Linq)\r\n\r\nclass Form24(Form):\r\n\tdef __init__(self, lstDdwnames, lstDdwids):\r\n\t\tself.Font = Font(self.Font.FontFamily, 16, FontStyle.Regular, GraphicsUnit.Pixel)\r\n\t\tself.autoName = \"Create New 3D View\"\r\n\t\tlstDdwnames.Add(self.autoName)\r\n\t\tlstDdwids.Add(self.autoName)\r\n\t\tself.listNames = lstDdwnames\r\n\t\tself._tableData = DataTable(\"Data\")\r\n\t\tself._tableData.Columns.Add(\"Key\", System.String)\r\n\t\tself._tableData.Columns.Add(\"Value\", System.Object)\r\n\t\t[self._tableData.Rows.Add(key_, value_ ) for key_, value_ in zip(lstDdwnames, lstDdwids)]\r\n\t\tself.out = []\r\n\t\tself.InitializeComponent()\r\n\t\r\n\tdef InitializeComponent(self):\r\n\t\tself._spr_top     = System.Windows.Forms.Label()\r\n\t\tself._comboBox1 = System.Windows.Forms.ComboBox()\r\n\t\tself._checkBoxSelect = System.Windows.Forms.CheckBox()\r\n\t\tself._button1 = System.Windows.Forms.Button()\r\n\t\tself._txtBlock2 = System.Windows.Forms.Label()\r\n\t\tself._txtBlock3 = System.Windows.Forms.Label()\r\n\t\tself._textBox1 = System.Windows.Forms.NumericUpDown()\r\n\t\tself.SuspendLayout()\r\n\t\t# \r\n\t\t# Separator Top\r\n\t\t# \r\n\t\tself._spr_top.Anchor     = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right\r\n\t\tself._spr_top.Location   = System.Drawing.Point(0, 0)\r\n\t\tself._spr_top.Name       = \"spr_top\"\r\n\t\tself._spr_top.Size       = System.Drawing.Size(2000, 2)\r\n\t\tself._spr_top.BackColor  = Color.FromArgb(82, 53, 239)\r\n\t\t# \r\n\t\t# checkedListBox1\r\n\t\t# \r\n\t\tself._comboBox1.Anchor = System.Windows.Forms.AnchorStyles.Top |  System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right\r\n\t\tself._comboBox1.FormattingEnabled = True\r\n\t\tself._comboBox1.Location = System.Drawing.Point(225, 12)\r\n\t\tself._comboBox1.Name = \"comboBox1\"\r\n\t\tself._comboBox1.DataSource = self._tableData \r\n\t\tself._comboBox1.DisplayMember = \"Key\"\r\n\t\tself._comboBox1.Size = System.Drawing.Size(175, 244)\r\n\t\tself._comboBox1.TabIndex = 0\r\n\t\tself._comboBox1.DropDownStyle = ComboBoxStyle.DropDownList\r\n\t\twidth = 195\r\n\t\tfor item in self.listNames:\r\n\t\t\ttemp = TextRenderer.MeasureText(item, self.Font).Width\r\n\t\t\tif width < temp:\r\n\t\t\t\twidth = temp\r\n\t\tself._comboBox1.DropDownWidth = width\r\n\t\t# \r\n\t\t# textBox1\r\n\t\t# \r\n\t\tself._textBox1.Anchor = System.Windows.Forms.AnchorStyles.Top |  System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right\r\n\t\tself._textBox1.Location = System.Drawing.Point(225, 47)\r\n\t\tself._textBox1.Name = \"textBox1\"\r\n\t\tself._textBox1.Size = System.Drawing.Size(175, 244)\r\n\t\tself._textBox1.DecimalPlaces = 2\r\n\t\tself._textBox1.TabIndex = 0\r\n\t\tself._textBox1.Value = IN[0]\r\n\t\tself._textBox1.Increment = IN[0]\r\n\t\tself._textBox1.Maximum = 999999999\r\n\t\t# \r\n\t\t# checkBoxSelectAll\r\n\t\t# \r\n\t\tself._checkBoxSelect.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left\r\n\t\tself._checkBoxSelect.Location = System.Drawing.Point(14, 80)\r\n\t\tself._checkBoxSelect.Name = \"checkBoxSelectAll\"\r\n\t\tself._checkBoxSelect.Size = System.Drawing.Size(395,24)\r\n\t\tself._checkBoxSelect.TabIndex = 1\r\n\t\tself._checkBoxSelect.Text = \"Add 3D view to side. Closes any other open view!\"\r\n\t\tself._checkBoxSelect.UseVisualStyleBackColor = True\r\n\t\t# \r\n\t\t# button1\r\n\t\t# \r\n\t\tself._button1.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right\r\n\t\tself._button1.Location = System.Drawing.Point(12, 110)\r\n\t\tself._button1.Name = \"button1\"\r\n\t\tself._button1.Size = System.Drawing.Size(388, 27)\r\n\t\tself._button1.TabIndex = 2\r\n\t\tself._button1.Text = \"Create Section Box in 3D View\"\r\n\t\tself._button1.UseVisualStyleBackColor = True\r\n\t\tself._button1.Click += self.Button1Click\r\n\t\t# \r\n\t\t# TextBlock2\r\n\t\t# \r\n\t\tself._txtBlock2.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left\r\n\t\tself._txtBlock2.Location = System.Drawing.Point(12, 15)\r\n\t\tself._txtBlock2.Name = \"txtBlock2\"\r\n\t\tself._txtBlock2.Size = System.Drawing.Size(200, 20)\r\n\t\tself._txtBlock2.TabIndex = 1\r\n\t\tself._txtBlock2.Text = \"Select 3D View:\"\r\n\t\t# \r\n\t\t# TextBlock3\r\n\t\t# \r\n\t\tself._txtBlock3.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left\r\n\t\tself._txtBlock3.Location = System.Drawing.Point(12, 50)\r\n\t\tself._txtBlock3.Name = \"txtBlock3\"\r\n\t\tself._txtBlock3.Size = System.Drawing.Size(210, 20)\r\n\t\tself._txtBlock3.TabIndex = 1\r\n\t\tself._txtBlock3.Text = \"Extra Size Section Box (ft):\"\r\n\t\t# \r\n\t\t# Form24\r\n\t\t# \r\n\t\tself.ClientSize = System.Drawing.Size(415, 150)\r\n\t\tself.CenterToScreen() \r\n\t\tself.FormBorderStyle = FormBorderStyle.FixedDialog\r\n\t\tself.MaximizeBox = False\r\n\t\tself.MinimizeBox = False\r\n\t\tself.Controls.Add(self._spr_top)\r\n\t\tself.Controls.Add(self._button1)\r\n\t\tself.Controls.Add(self._checkBoxSelect)\r\n\t\tself.Controls.Add(self._comboBox1)\r\n\t\tself.Controls.Add(self._textBox1)\r\n\t\tself.Controls.Add(self._txtBlock2)\r\n\t\tself.Controls.Add(self._txtBlock3)\r\n\t\tself.Name = \"To 3D View Extended\"\r\n\t\tself.Text = \"To 3D View Extended\"\r\n\t\ticonFilename = 'C:\\\\NONICAPRO\\\\OtherFiles\\\\System\\\\Nonicafavicon.ICO'\r\n\t\tif not os.path.exists(iconFilename):\r\n\t\t\ticonFilename = 'C:\\\\NONICA\\\\OtherFiles\\\\System\\\\Nonicafavicon.ICO'\r\n\t\ticon = Icon(iconFilename)\r\n\t\tself.Icon = icon\r\n\t\tself.ResumeLayout(False)\t\t\r\n\t\t\t\r\n\tdef Button1Click(self, sender, e):\r\n\t\ttry:\r\n\t\t\tif self._comboBox1.Text != self.autoName:\r\n\t\t\t\tsel_item = self._comboBox1.SelectedItem['Value']\r\n\t\t\telse:\r\n\t\t\t\tsel_item = -1\r\n\t\t\tself.sel_cmb = sel_item\r\n\t\t\tself.extra_size = self._textBox1.Value\r\n\t\t\tself.add_to_side = self._checkBoxSelect.CheckState\r\n\t\t\tself.DialogResult = DialogResult.Yes\r\n\t\t\tself.Close()\r\n\t\texcept:\r\n\t\t\tpass\r\n\r\ndef pickobject():\r\n\tfrom Autodesk.Revit.UI.Selection import ObjectType\r\n\tpicked = uidoc.Selection.PickObjects(ObjectType.Element)\r\n\treturn picked\r\n\r\ndef isclose(a, b, rel_tol=1e-09, abs_tol=0.0):\r\n\treturn abs(a-b) <= max(rel_tol * max(abs(a), abs(b)), abs_tol)\r\n\r\ndef compareXYZ(firstpoint, secondpoint):\r\n\tif isclose(firstpoint.X, secondpoint.X) and isclose(firstpoint.Y, secondpoint.Y) and isclose(firstpoint.Z, secondpoint.Z):\r\n\t\treturn 1\r\n\telse:\r\n\t\treturn 0\r\n\r\nextra_size=IN[0]\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\napp = doc.Application\r\nuiapp = DocumentManager.Instance.CurrentUIApplication\r\nuidoc = uiapp.ActiveUIDocument\r\n\r\npicked_obj = List[ElementId]()\r\nif uidoc.Selection.GetElementIds().Count == 0:\r\n\t#Nothing selected, let the user select\r\n\ttry:\r\n\t\tpicked_obj = pickobject()\r\n\texcept:\r\n\t\tpass\r\nelse:\r\n\tpicked_obj = uidoc.Selection.GetElementIds()\r\n\t\r\nif picked_obj.Count == 0:\r\n\t#Indicate user, no element has been selected\r\n\ttask2 = Autodesk.Revit.UI.TaskDialog(\"To 3D View Extended\")\r\n\ttask2.MainInstruction = \"No elements were selected. Please, select them before or after running.\"\r\n\ttask2.Show()\r\nelse:\r\n\t#Get all 3dviews and ids\r\n\tall_3dviews = FilteredElementCollector(doc).OfClass(View3D).ToElements()\r\n\tlist_names =[]\r\n\tlist_ids=[]\r\n\tfor view in all_3dviews:\r\n\t\tif view.IsTemplate == False:\r\n\t\t\tlist_names.append(view.Title)\r\n\t\t\tlist_ids.append(view.Id)\r\n\tzipeo = zip(list_names,list_ids)\r\n\tzipeo = sorted(zipeo, key = lambda x: x[0])\r\n\tlist_names = [x for x,y in zipeo]\r\n\tlist_ids = [y for x,y in zipeo]\r\n\t#Create window\r\n\tobjForm = Form24(list_names, list_ids)\r\n\tresult_win = objForm.ShowDialog()\r\n\tif result_win == DialogResult.Cancel:\r\n\t\tOUT=0\r\n\telse:\r\n\t\t#To 3d view\r\n\t\told_activeView = doc.ActiveView\r\n\t\t#Get values from window\r\n\t\tif objForm.sel_cmb != -1:\r\n\t\t\tdefault_threeD_view = doc.GetElement(objForm.sel_cmb)\r\n\t\telse:\r\n\t\t\tdefaultname = \"Default 3D View with SectionBox\"\r\n\t\t\tcounter = 0\r\n\t\t\twhile True:\r\n\t\t\t\tviews_model = [x for x in FilteredElementCollector(doc).OfClass(Autodesk.Revit.DB.View).ToElements() if x.ViewType == ViewType.ThreeD and x.Name == defaultname]\r\n\t\t\t\tif len(views_model) == 0:\r\n\t\t\t\t\tbreak\r\n\t\t\t\telse:\r\n\t\t\t\t\tcounter+=1\r\n\t\t\t\t\tdefaultname = \"Default 3D View with SectionBox(\" + str(counter) + \")\"\r\n\t\t\t#TransactionManager.Instance.EnsureInTransaction(doc)\r\n\t\t\twith Transaction(doc, \"To 3D View: Create View\") as t:\r\n\t\t\t\tt.Start()\r\n\t\t\t\tdefault_threeD_view = View3D.CreateIsometric(doc, doc.GetDefaultElementTypeId(ElementTypeGroup.ViewType3D))\r\n\t\t\t\tdefault_threeD_view.Name = defaultname\r\n\t\t\t\tt.Commit()\r\n\t\t\t#TransactionManager.Instance.TransactionTaskDone()\r\n\t\t#TransactionManager.Instance.ForceCloseTransaction();\r\n\t\tuidoc.RequestViewChange(default_threeD_view)\r\n\t\t#Hide current section box\r\n\t\t#TransactionManager.Instance.EnsureInTransaction(doc)\r\n\t\twith Transaction(doc, \"To 3D View: Prepare View\") as t:\r\n\t\t\tt.Start()\r\n\t\t\tdefault_threeD_view.IsSectionBoxActive = False\t\r\n\t\t\tt.Commit()\r\n\t\t#TransactionManager.Instance.TransactionTaskDone()\r\n\t\tMax_XList = []\r\n\t\tMin_XList = []\r\n\t\tMax_YList = []\r\n\t\tMin_YList = []\r\n\t\tMax_ZList = []\r\n\t\tMin_ZList = []\r\n\t\tlist_ele = List[ElementId]()\r\n\t\teleSet = ElementSet()\r\n\t\tfor obj in picked_obj:\r\n\t\t\telem = doc.GetElement(obj)\r\n\t\t\tlist_ele.Add(elem.Id)\r\n\t\t\teleSet.Insert(elem)\r\n\t\t\ttry:\r\n\t\t\t\tbbox = elem.get_BoundingBox(default_threeD_view)\r\n\t\t\t\tMax_XList.append(bbox.Max.X)\r\n\t\t\t\tMin_XList.append(bbox.Min.X)\r\n\t\t\t\tMax_YList.append(bbox.Max.Y)\r\n\t\t\t\tMin_YList.append(bbox.Min.Y)\r\n\t\t\t\tMax_ZList.append(bbox.Max.Z)\r\n\t\t\t\tMin_ZList.append(bbox.Min.Z)\r\n\t\t\texcept:\r\n\t\t\t\tpass\r\n\t\textra_size = objForm.extra_size\r\n\t\tbox_created=0\r\n\t\t#Get max and min coord\r\n\t\ttry:\r\n\t\t\tX_Max = max(Max_XList)\r\n\t\t\tX_Min = min(Min_XList)\r\n\t\t\tY_Max = max(Max_YList)\r\n\t\t\tY_Min = min(Min_YList)\r\n\t\t\tZ_Max = max(Max_ZList)\r\n\t\t\tZ_Min = min(Min_ZList)\r\n\t\t\tmax_coord = XYZ(X_Max+extra_size, Y_Max+extra_size, Z_Max+extra_size)\r\n\t\t\tmin_coord = XYZ(X_Min-extra_size, Y_Min-extra_size, Z_Min-extra_size)\r\n\t\t\tfor elemento_id in list_ele:\r\n\t\t\t\telemento = doc.GetElement(elemento_id)\r\n\t\t\t\tif elemento.Category != None:\r\n\t\t\t\t\tif elemento.Category.Id == ElementId(BuiltInCategory.OST_VolumeOfInterest):\r\n\t\t\t\t\t\tbbox = elemento.get_BoundingBox(None)\r\n\t\t\t\t\t\tif isclose(bbox.Max.X, X_Max) ==1 and isclose(bbox.Max.Y, Y_Max) ==1 and isclose(bbox.Max.Z, Z_Max) ==1 and isclose(bbox.Min.X, X_Min) ==1 and isclose(bbox.Min.Y, Y_Min) ==1 and isclose(bbox.Min.Z, Z_Min) ==1:\r\n\t\t\t\t\t\t\t#Scope Box is larger element, check if rotated\r\n\t\t\t\t\t\t\t#Scope box geometry\t\t\t\t\t\r\n\t\t\t\t\t\t\topt = app.Create.NewGeometryOptions()\r\n\t\t\t\t\t\t\tgeo = elemento.get_Geometry(opt)\r\n\t\t\t\t\t\t\tlist_all_points = []\r\n\t\t\t\t\t\t\tlist_lower_points = []\r\n\t\t\t\t\t\t\t#Find z\r\n\t\t\t\t\t\t\tmax_z = bbox.Max.Z\r\n\t\t\t\t\t\t\tmin_z = bbox.Min.Z\r\n\t\t\t\t\t\t\tnormal_vectors = []\r\n\t\t\t\t\t\t\tortho_box=0\r\n\t\t\t\t\t\t\t#Find 8 points of scope and lower face points\r\n\t\t\t\t\t\t\tfor obj in geo:\r\n\t\t\t\t\t\t\t\tp=obj.GetEndPoint(0)\r\n\t\t\t\t\t\t\t\tq=obj.GetEndPoint(1)\r\n\t\t\t\t\t\t\t\tif not obj.Direction.IsAlmostEqualTo(XYZ(0,0,-1)) and not obj.Direction.IsAlmostEqualTo(XYZ(0,0,1)):\r\n\t\t\t\t\t\t\t\t\tnormal_vectors.Add(obj.Direction)\r\n\t\t\t\t\t\t\t\t\tif obj.Direction.IsAlmostEqualTo(XYZ(0,-1,0)) or obj.Direction.IsAlmostEqualTo(XYZ(0,1,0)) or obj.Direction.IsAlmostEqualTo(XYZ(-1,0,0)) or obj.Direction.IsAlmostEqualTo(XYZ(1,0,0)):\r\n\t\t\t\t\t\t\t\t\t\tortho_box=1\r\n\t\t\t\t\t\t\t\tchecker_initial = 0\r\n\t\t\t\t\t\t\t\tchecker_end = 0\r\n\t\t\t\t\t\t\t\tfor other_point in list_all_points:\r\n\t\t\t\t\t\t\t\t\tif compareXYZ(p, other_point)==1:\r\n\t\t\t\t\t\t\t\t\t\tchecker_initial=1\r\n\t\t\t\t\t\t\t\t\tif compareXYZ(q, other_point)==1:\r\n\t\t\t\t\t\t\t\t\t\tchecker_end=1\r\n\t\t\t\t\t\t\t\tif checker_initial==0:\r\n\t\t\t\t\t\t\t\t\tlist_all_points.append(p)\r\n\t\t\t\t\t\t\t\t\tif isclose(p.Z, min_z):\r\n\t\t\t\t\t\t\t\t\t\tlist_lower_points.append(p)\r\n\t\t\t\t\t\t\t\tif checker_end==0:\r\n\t\t\t\t\t\t\t\t\tlist_all_points.append(q)\r\n\t\t\t\t\t\t\t\t\tif isclose(q.Z, min_z):\r\n\t\t\t\t\t\t\t\t\t\tlist_lower_points.append(q)\r\n\t\t\t\t\t\t\t#Find size of box\r\n\t\t\t\t\t\t\t#Get edge sizes\r\n\t\t\t\t\t\t\tfor point in list_lower_points:\r\n\t\t\t\t\t\t\t\tif isclose(point.X, X_Min)==1:\r\n\t\t\t\t\t\t\t\t\tpunto1=point\r\n\t\t\t\t\t\t\t\tif isclose(point.Y, Y_Min)==1:\r\n\t\t\t\t\t\t\t\t\tpunto2=point\r\n\t\t\t\t\t\t\t\tif isclose(point.X, X_Max)==1:\r\n\t\t\t\t\t\t\t\t\tpunto3=point\r\n\t\t\t\t\t\t\tedge1=punto2.DistanceTo(punto1)\r\n\t\t\t\t\t\t\tedge2=punto2.DistanceTo(punto3)\r\n\t\t\t\t\t\t\t#Find angle\r\n\t\t\t\t\t\t\taxis_y = XYZ(0,1,0)\r\n\t\t\t\t\t\t\tvector = punto3-punto2\r\n\t\t\t\t\t\t\tangle_to_rotate = axis_y.AngleTo(vector)\r\n\t\t\t\t\t\t\t#Check box is not orthogonal\r\n\t\t\t\t\t\t\tif ortho_box==1:\r\n\t\t\t\t\t\t\t\tmyBox = BoundingBoxXYZ()\r\n\t\t\t\t\t\t\t\tmyBox.Min = min_coord\r\n\t\t\t\t\t\t\t\tmyBox.Max = max_coord\r\n\t\t\t\t\t\t\t\tbox_created=1\r\n\t\t\t\t\t\t\telse:\r\n\t\t\t\t\t\t\t\tmyBox = BoundingBoxXYZ()\r\n\t\t\t\t\t\t\t\tmyBox.Min = XYZ(punto2.X-edge1-extra_size-extra_size, Y_Min, Z_Min)\r\n\t\t\t\t\t\t\t\tmyBox.Max = XYZ(punto2.X, punto2.Y+edge2+extra_size+extra_size, Z_Max+extra_size+extra_size)\r\n\t\t\t\t\t\t\t\taxis_z = XYZ(0,0,1)\r\n\t\t\t\t\t\t\t\trotate = Transform.CreateRotationAtPoint(axis_z, -angle_to_rotate, punto2)\r\n\t\t\t\t\t\t\t\tmyBox.Transform = myBox.Transform.Multiply(rotate)\r\n\t\t\t\t\t\t\t\tbox_created=1\r\n\t\t\t\t\t\t\t\t#Center axisX\r\n\t\t\t\t\t\t\t\tvectorX = (punto2-punto1).Normalize() * extra_size\r\n\t\t\t\t\t\t\t\ttransx =Transform.CreateTranslation(vectorX)\r\n\t\t\t\t\t\t\t\tmyBox.Transform = myBox.Transform.Multiply(transx)\r\n\t\t\t\t\t\t\t\t#Center axisY\r\n\t\t\t\t\t\t\t\tvectorY = (punto2-punto3).Normalize() * extra_size\r\n\t\t\t\t\t\t\t\ttransY =Transform.CreateTranslation(vectorY)\r\n\t\t\t\t\t\t\t\tmyBox.Transform = myBox.Transform.Multiply(transY)\r\n\t\t\t\t\t\t\t\t#Center axisZ\r\n\t\t\t\t\t\t\t\tvectorZ = XYZ(0,0,-1) * extra_size\r\n\t\t\t\t\t\t\t\ttransZ =Transform.CreateTranslation(vectorZ)\r\n\t\t\t\t\t\t\t\tmyBox.Transform = myBox.Transform.Multiply(transZ)\r\n\t\t\tif box_created==0:\r\n\t\t\t\tmyBox = BoundingBoxXYZ()\r\n\t\t\t\tmyBox.Min = min_coord\r\n\t\t\t\tmyBox.Max = max_coord\t\r\n\t\t\t#AsignasBoundingBox\r\n\t\t\t#TransactionManager.Instance.EnsureInTransaction(doc)\r\n\t\t\twith Transaction(doc, \"To 3D View Extended\") as t:\r\n\t\t\t\tt.Start()\r\n\t\t\t\tdefault_threeD_view.SetSectionBox(myBox)\r\n\t\t\t\tt.Commit()\r\n\t\t\t\t#TransactionManager.Instance.TransactionTaskDone()\r\n\t\t\tuidoc.ShowElements(eleSet)\r\n\t\t\tuidoc.Selection.SetElementIds(list_ele)\r\n\t\t\t#Side by side\r\n\t\t\tif objForm.add_to_side == CheckState.Checked:\r\n\t\t\t\t#Close all other Windows but current and 3D\r\n\t\t\t\tfor openVw in uidoc.GetOpenUIViews():\r\n\t\t\t\t\tview=doc.GetElement(openVw.ViewId)\r\n\t\t\t\t\tif str(openVw.ViewId) != str(default_threeD_view.Id) and str(openVw.ViewId) != str(old_activeView.Id):\r\n\t\t\t\t\t\topenVw.Close()\t\t\t\t\r\n\t\t\t\t#Call side by side postcommand\r\n\t\t\t\tcommandId = RevitCommandId.LookupPostableCommandId(PostableCommand.TileViews)\r\n\t\t\t\tif uiapp.CanPostCommand(commandId):\r\n\t\t\t\t\tuiapp.PostCommand(commandId)\r\n\t\texcept Exception as e:\r\n\t\t\ttask2 = Autodesk.Revit.UI.TaskDialog(\"To 3D View Extended\")\r\n\t\t\ttask2.MainInstruction = \"Section Box cannot be created for this element/s.\"\r\n\t\t\ttask2.Show()\r\nOUT=0\r\n\"\"\"\r\nYou agreed to the following license terms and conditions. They are also applicable to obtaining and using this script:\r\nLicense Agreement\r\nFor use of NonicaTab PRO.\r\nThis License Agreement (this “Agreement” of this “License Agreement”) is made and effective as of the current date (the “Commencement Date”) by and between Nonica by Nonica Enterprise SL a company organized and existing in Spain with a registered address at Avd.Chafarinas 16 Spain (“Licensor”) and yourself (“Licensee”).\r\nWHEREAS:\r\n1.\tLicensee wishes to obtain access and use this script (hereinafter, the “Asset”), and\r\n2.\tLicensor is willing to grant to the Licensee a non-exclusive, non-transferable License to use the Asset for the term and specific purpose set forth in this Agreement,\r\nNOW, THEREFORE, your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or use NonicaTab PRO and its derivative files and scripts.\r\n1. Definitions\r\n1.1 “Agreement” means this License Agreement including the attached Schedule.\r\n1.2 “Confidential Information” means information that:\r\na. is by its nature confidential;\r\nb. is designated in writing by Licensor as confidential;\r\nc. the Licensee knows or reasonably ought to know is confidential;\r\nd. Information comprised in or relating to any Intellectual Property Rights of Licensor.\r\n1.3 “Asset” means the Asset provided by Licensor as specified in Item 6 of the Schedule in the form as stated in Item 7 of the Schedule.\r\n1.4 “Intellectual Property Rights” means all rights in and to any copyright, trademark, trading name, design, patent, know how (trade secrets) and all other rights resulting from intellectual activity in the industrial, scientific, literary or artistic field and any application or right to apply for registration of any of these rights and any right to protect or enforce any of these rights, as further specified in clause 5.\r\n1.5 “Party” means a person or business entity who has executed this Agreement; details of the Parties are specified in Item 2 of the Schedule.\r\n1.6 “Term” means the term of this Agreement commencing on the Commencement Date as specified in Item 4 of the Schedule and expiring on the Expiry Date specified in Item 5 of the Schedule.\r\n2. License Grant\r\n2.1 Licensor grants to the Licensee a non-exclusive, non-transferable License for the Term to use the Asset for the specific purpose specified in this Agreement, subject to the terms and conditions set out in this Agreement.\r\n3. Charges\r\n3.1 In consideration of the Licensor providing the License under clause 2 of this License Agreement, the Licensee agrees to pay Licensor the amount of the License Charge as specified in Item 9 of the Schedule.\r\n4. Licensee’s Obligations\r\n4.1 The Licensee cannot use the Asset, for purposes other than as specified in this Agreement and in Item 8 of the Schedule.\r\n4.2 The Licensee may permit its employees to use the Asset for the purposes described in Item 8, provided that the Licensee takes all necessary steps and imposes the necessary conditions to ensure that all employees using the Asset do not commercialise or disclose the contents of it to any third person, or use it other than in accordance with the terms of this Agreement.\r\n4.3 The Licensee will not distribute, sell, License or sub-License, let, trade or expose for sale the Asset to a third party.\r\n4.4 No copies of the Asset are to be made other than as expressly approved by Licensor.\r\n4.5 No changes to the Asset or its content may be made by Licensee.\r\n4.6 The Licensee will provide technological and security measures to ensure that the Asset which the Licensee is responsible for is physically and electronically secure from unauthorised use or access.\r\n4.7 Licensee shall ensure that the Asset retains all Licensor copyright notices and other proprietary legends and all trademarks or service marks of Licensor.\r\n5. Intellectual Property Rights\r\n5.1 All Intellectual Property Rights over and in respect of the Asset are owned by Licensor. The Licensee does not acquire any rights of ownership in the Asset.\r\n6. Limitation of Liability\r\n6.1 The Licensee acknowledges and agrees that neither Licensor nor its board members, officers, employees or agents, will be liable for any loss or damage arising out of or resulting from Licensor’s provision of the Asset under this Agreement, or any use of the Asset by the Licensee or its employees; and Licensee hereby releases Licensor to the fullest extent from any such liability, loss, damage or claim.\r\n7. Confidentiality\r\n7.1 Neither Party may use, disclose or make available to any third party the other Party’s Confidential Information, unless such use or disclosure is done in accordance with the terms of this Agreement.\r\n7.2 Each Party must hold the other Party’s Confidential Information secure and in confidence, except to the extent that such Confidential Information:\r\na. is required to be disclosed according to the requirements of any law, judicial or legislative body or government agency; or\r\nb. was approved for release in writing by the other Party, but only to the extent of and subject to such conditions as may be imposed in such written authorisation.\r\n7.3 This clause 7 will survive termination of this Agreement.\r\n8. Disclaimers & Release\r\n8.1 To the extent permitted by law, Licensor will in no way be liable to the Licensee or any third party for any loss or damage, however caused (including through negligence) which may be directly or indirectly suffered in connection with any use of the Asset.\r\n8.2 The Asset is provided by Licensor on an “as is” basis.\r\n8.3 Licensor will not be held liable by the Licensee in any way, for any loss, damage or injury suffered by the Licensee or by any other person related to any use of the Asset or any part thereof.\r\n8.4 Notwithstanding anything contained in this Agreement, in no event shall Licensor be liable for any claims, damages or loss which may arise from the modification, combination, operation or use of the Asset with Licensee computer programs.\r\n8.5 Licensor does not warrant that the Asset will function in any environment.\r\n8.6 The Licensee acknowledges that: a. The Asset has not been prepared to meet any specific requirements of any party, including any requirements of Licensee; and b. it is therefore the responsibility of the Licensee to ensure that the Asset meets its own individual requirements.\r\n8.7 To the extent permitted by law, no express or implied warranty, term, condition or undertaking is given or assumed by Licensor, including any implied warranty of merchantability or fitness for a particular purpose.\r\n9. Indemnification\r\n9.1 The Licensee must indemnify, defend and hold harmless Licensor, its board members, officers, employees and agents from and against any and all claims (including third party claims), demands, actions, suits, expenses (including attorney’s fees) and damages (including indirect or consequential loss) resulting in any way from:\r\na. Licensee’s and Licensee’s employee’s use or reliance on the Asset,\r\nb. any breach of the terms of this License Agreement by the Licensee or any Licensee employee, and\r\nc. any other act of Licensee.\r\n9.2 This clause 9 will survive termination of this Agreement.\r\n10. Waiver\r\n10.1 Any failure or delay by either Party to exercise any right, power or privilege hereunder or to insist upon observance or performance by the other of the provisions of this License Agreement shall not operate or be construed as a waiver thereof.\r\n11. Governing Law\r\n11.1 This Agreement will be construed by and governed in accordance with the laws of Spain. The Parties submit to exclusive jurisdiction of the courts of Spain.\r\n12. Termination\r\n12.1 This Agreement and the License granted herein commences upon the Commencement Date and is granted for the Term, unless otherwise terminated by Licensor in the event of any of the following:\r\na. if the Licensee is in breach of any term of this License Agreement and has not corrected such breach to Licensor’s reasonable satisfaction within 7 days of Licensor’s notice of the same;\r\nb. if the Licensee becomes insolvent, or institutes (or there is instituted against it) proceedings in bankruptcy, insolvency, reorganization or dissolution, or makes an assignment for the benefit of creditors; or\r\nc. the Licensee is in breach of clause 5 or 7 of this Agreement.\r\n12.2 Termination under this clause shall not affect any other rights or remedies Licensor may have.\r\n14. Assignment\r\n14.1 Licensee shall not assign any rights of this License Agreement, without the prior written consent of Licensor.\r\n15. Notices\r\n15.1 All notices required under this Agreement shall be in writing and shall be deemed given (i) when delivered personally; (ii) five (5) days after mailing, when sent certified mail, return receipt requested and postage prepaid; or (iii) one (1) business day after dispatch, when sent via a commercial overnight carrier, fees prepaid. All notices given by either Party must be sent to the address of the other as first written above (unless otherwise changed by written notice).\r\n15.2 Autodesk username, Autodesk Internal ID number and unique identifiers of hardware in your computer are stored in a speciliazed third party cloud server for licensing purposes. This information is neccessary for using NonicaTab PRO. The licensee maintains its full right to delete/remove such information if declining the renewal of the software. NonicaTab PRO will not shared that information with any third party company unless it is required judicially by law. Please contact hello@nonica.io with any further doubt/request.\r\n16. Counterparts\r\n16.1 This Agreement may be executed in any number of counterparts, each of which shall be deemed to be an original and all of which taken together shall constitute one instrument.\r\n17. Severability\r\n17.1 The Parties recognize the uncertainty of the law with respect to certain provisions of this Agreement and expressly stipulate that this Agreement will be construed in a manner that renders its provisions valid and enforceable to the maximum extent possible under applicable law. To the extent that any provisions of this Agreement are determined by a court of competent jurisdiction to be invalid or unenforceable, such provisions will be deleted from this Agreement or modified so as to make them enforceable and the validity and enforceability of the remainder of such provisions and of this Agreement will be unaffected.\r\n18. Entire Agreement\r\n18.1 This Agreement contains the entire agreement between the Parties and supersedes any previous understanding, commitments or agreements, oral or written. Further, this Agreement may not be modified, changed, or otherwise altered in any respect except by a written agreement signed by both Parties.\r\nIN WITNESS WHEREOF, this Agreement, including the attached Schedule, was signed by the Parties under the hands of their duly authorized representatives and made effective as of the current date.\r\nNonica by Nonica Enterprise SL,\r\nSignature\r\n10/04/2025\r\nJaime Alonso Candau\r\nPlease contact hello@nonica.io with any further doubt/request.\r\nYour signatureby using and accessing this script.\r\nSigned by accepting these terms.\r\nCurrent date.\r\n\"\"\"",
      "VariableInputPorts": true,
      "Id": "b2265ed3a9f540d597c07b31a23850a9",
      "Inputs": [
        {
          "Id": "4d9504cf89a2400aa86b38d156ff49fe",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "e233b787a3834e41b6cc71fedfd4b97d",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "InputValue": 0.5,
      "Id": "198f8e6287b94e3faeb1e9ffd62a51ef",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "8ad9363989964b2683e7ef87354eb4de",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number."
    }
  ],
  "Connectors": [
    {
      "Start": "8ad9363989964b2683e7ef87354eb4de",
      "End": "4d9504cf89a2400aa86b38d156ff49fe",
      "Id": "b8fffd4432bd428eb449746df26eb612"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.6.2.15705",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Extended",
        "Id": "b2265ed3a9f540d597c07b31a23850a9",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -366.05439524619783,
        "Y": 284.66261880618214
      },
      {
        "ShowGeometry": true,
        "Name": "Default Extra size (in feet)",
        "Id": "198f8e6287b94e3faeb1e9ffd62a51ef",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -612.452086124249,
        "Y": 286.52587856138507
      }
    ],
    "Annotations": [],
    "X": 781.11935515410732,
    "Y": -126.98825077254725,
    "Zoom": 1.1480753736589788
  }
}