{
  "Uuid": "f710d647-f4c9-463c-bc3f-a9de4bb7ba58",
  "IsCustomNode": false,
  "Description": null,
  "Name": "JoinInView",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import sys\r\nimport clr\r\nimport os\r\nimport ctypes\r\nfrom ctypes import wintypes\r\nfrom ctypes.wintypes import MAX_PATH\r\n\r\nfrom System import Array\r\nfrom System.Collections.Generic import *\r\n\r\nfrom operator import attrgetter\r\n\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript.Geometry import *\r\n\r\nclr.AddReference('RevitAPI')\r\nimport Autodesk\r\nfrom Autodesk.Revit.DB import *\r\n\r\nclr.AddReference(\"RevitAPIUI\")\r\nimport Autodesk \r\nfrom Autodesk.Revit.UI import TaskDialog, IExternalEventHandler, ExternalEvent\r\nfrom Autodesk.Revit.UI.Selection import *\r\n\r\nclr.AddReference(\"RevitServices\")\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\n\r\nclr.AddReference('RevitAPIIFC')\r\nfrom Autodesk.Revit.DB.IFC import *\r\n\r\nclr.AddReference('System.Drawing')\r\nclr.AddReference('System.Windows.Forms')\r\nimport System.Drawing\r\nimport System.Windows.Forms\r\nfrom System.Drawing import *\r\nfrom System.Reflection import Assembly\r\nfrom System.Windows.Forms import *\r\n\r\nclr.AddReference('System.Data')\r\nfrom System.Data import *\r\n\r\nclass UnsubcribeDocChange(IExternalEventHandler):\r\n\tdef __init__(self):\r\n\t\tpass\r\n\t\t\r\n\tdef Execute(self, uiapp):\r\n\t\ttry:\r\n\t\t\tuiapp.ViewActivated -= new_sub\r\n\t\texcept Exception as e:\r\n\t\t\tpass\r\n\t\t\t\r\n\tdef GetName(self):\r\n\t\treturn \"Unsubscribe Document Changed Event\"\r\n\r\nclass joinElements(IExternalEventHandler):\r\n\tdef __init__(self, pri_cat):\r\n\t\tself.cat_priorities = pri_cat\r\n\r\n\tdef Execute(self, uiapp):\r\n\t\ttry:\r\n\t\t\tcat_names, cat_builtin = extractListsPriorities()\r\n\t\t\tif len(cat_names) != 0:\r\n\t\t\t\tself.cat_priorities = cat_builtin\r\n\t\t\tui_doc = uiapp.ActiveUIDocument\r\n\t\t\tglobal new_doc\r\n\t\t\tnew_doc = ui_doc.Document\r\n\t\t\tviews_sel = [item['Value'] for item in objForm.checkedListBox1.CheckedItems]\r\n\t\t\tcategories_sel = [item['Value'] for item in objForm.checkedListBox2.CheckedItems]\r\n\t\t\t#If selection\r\n\t\t\tif objForm.checkBox1.Checked == True:\r\n\t\t\t\tselected_ids = uidoc.Selection.GetElementIds()\r\n\t\t\t\tif len(selected_ids) == 0:\r\n\t\t\t\t\ttry:\r\n\t\t\t\t\t\t#Change text in button join elements\r\n\t\t\t\t\t\tobjForm.button2.Text = \"Select in Revit\"\r\n\t\t\t\t\t\tobjForm.button2.Enabled = False\r\n\t\t\t\t\t\tsel_refs = uidoc.Selection.PickObjects(ObjectType.Element, \"Select Elements in Revit\")\r\n\t\t\t\t\t\tobjForm.button2.Enabled = True\r\n\t\t\t\t\t\tobjForm.button2.Text = \"Join Elements!\"\r\n\t\t\t\t\t\t#Filter elements and count\r\n\t\t\t\t\t\tids_ele = [x.ElementId for x in sel_refs]\r\n\t\t\t\t\t\tfil_eles = self.filteredElementsCategories(ids_ele, categories_sel)\r\n\t\t\t\t\t\tif len(fil_eles) > 1:\r\n\t\t\t\t\t\t\tuiapp.Application.FailuresProcessing += failureProc\r\n\t\t\t\t\t\t\tself.executeJoinElements(fil_eles, None, categories_sel)\r\n\t\t\t\t\t\t\tuiapp.Application.FailuresProcessing -= failureProc\r\n\t\t\t\t\t\telse:\r\n\t\t\t\t\t\t\tself.windowNothingSelected()\r\n\t\t\t\t\texcept Exception as exc:\r\n\t\t\t\t\t\tobjForm.button2.Enabled = True\r\n\t\t\t\t\t\tobjForm.button2.Text = \"Join Elements!\"\r\n\t\t\t\t\t\tself.windowNothingSelected()\r\n\t\t\t\telse:\r\n\t\t\t\t\t#Filter elements and count\r\n\t\t\t\t\tfil_eles = self.filteredElementsCategories(selected_ids, categories_sel)\r\n\t\t\t\t\tif len(fil_eles) > 1:\r\n\t\t\t\t\t\tuiapp.Application.FailuresProcessing += failureProc\r\n\t\t\t\t\t\tself.executeJoinElements(fil_eles, None, categories_sel)\r\n\t\t\t\t\t\tuiapp.Application.FailuresProcessing -= failureProc\r\n\t\t\t\t\telse:\r\n\t\t\t\t\t\tself.windowNothingSelected()\r\n\t\t\telse:\r\n\t\t\t\t#Get Elements in views\r\n\t\t\t\tuiapp.Application.FailuresProcessing += failureProc\r\n\t\t\t\tshowed_window = False\r\n\t\t\t\tshould_show = False\r\n\t\t\t\tnumber_views = len(views_sel)\r\n\t\t\t\t#ProgressBar\r\n\t\t\t\tcountIssues = 0\r\n\t\t\t\tprogressForm = FormWithProgresBar()\r\n\t\t\t\tprogressForm._progressBar.Minimum = 0\r\n\t\t\t\tprogressForm._progressBar.Maximum = number_views\r\n\t\t\t\tprogressForm._progressBar.Step = 1\r\n\t\t\t\tobjForm.Hide()\r\n\t\t\t\tprogressForm.Show()\r\n\t\t\t\twith TransactionGroup(new_doc, \"Join in Views\") as tg:\r\n\t\t\t\t\ttg.Start()\r\n\t\t\t\t\tfor vw_id in views_sel:\r\n\t\t\t\t\t\tprogressForm._txtBlock2.Text = str(countIssues) + \" / \" + str(number_views) + \" Views Processed\"\r\n\t\t\t\t\t\tprogressForm._progressBar.PerformStep()\r\n\t\t\t\t\t\tprogressForm.Refresh()\r\n\t\t\t\t\t\tApplication.DoEvents()\r\n\t\t\t\t\t\tif progressForm.interrupt == True:\r\n\t\t\t\t\t\t\tbreak\r\n\t\t\t\t\t\tcountIssues+= 1\r\n\t\t\t\t\t\tall_ele_in_view = self.getAllElementsToJoin(categories_sel, vw_id)\r\n\t\t\t\t\t\tif len(all_ele_in_view) > 1:\r\n\t\t\t\t\t\t\tself.executeJoinElements(all_ele_in_view, vw_id, categories_sel)\r\n\t\t\t\t\t\t\tshowed_window = True\r\n\t\t\t\t\t\telse:\r\n\t\t\t\t\t\t\tshould_show = True\r\n\t\t\t\t\tif should_show and showed_window == False:\r\n\t\t\t\t\t\tshowed_window = True\r\n\t\t\t\t\t\tprogressForm.Hide()\r\n\t\t\t\t\t\tAutodesk.Revit.UI.TaskDialog.Show(\"Join In Views\",\"Please, select view/s that at least have 2 elements of the selected categories to join.\")\r\n\t\t\t\t\t#Cancelled process\r\n\t\t\t\t\tif progressForm.interrupt == True:\r\n\t\t\t\t\t\ttg.RollBack()\r\n\t\t\t\t\t\tprogressForm.Close()\r\n\t\t\t\t\t\tAutodesk.Revit.UI.TaskDialog.Show(\"Process Cancelled\",\"The process has been interrupted. Any change done during the process was undo.\")\r\n\t\t\t\t\telse:\r\n\t\t\t\t\t\ttg.Assimilate()\r\n\t\t\t\tprogressForm.Close()\t\t\t\t\t\t\r\n\t\t\t\tobjForm.Show()\r\n\t\t\t\tuiapp.Application.FailuresProcessing -= failureProc\r\n\t\texcept Exception as e:\r\n\t\t\tAutodesk.Revit.UI.TaskDialog.Show(\"Exception\",str(e))\r\n\t\t\t\r\n\tdef executeJoinElements(self, joinable_elements, view_id, sel_cats):\r\n\t\ttry:\r\n\t\t\tjoined_elements = {}\r\n\t\t\tif view_id:\r\n\t\t\t\tview_ele = new_doc.GetElement(view_id)\r\n\t\t\telse:\r\n\t\t\t\tview_ele = None\r\n\t\t\t\tcountIssues = 0\r\n\t\t\t\tprogressForm = FormWithProgresBar()\r\n\t\t\t\tnumber_ele = len(joinable_elements)\r\n\t\t\t\tprogressForm._progressBar.Minimum = 0\r\n\t\t\t\tprogressForm._progressBar.Maximum = number_ele\r\n\t\t\t\tprogressForm._progressBar.Step = 1\r\n\t\t\t\tprogressForm._txtBlock2.Text = \"0 / \" + str(number_ele) + \" Elements Processed\"\r\n\t\t\t\tobjForm.Hide()\r\n\t\t\t\tprogressForm.Show()\r\n\t\t\twith Transaction(new_doc, \"Join Elements\") as trans:\r\n\t\t\t\ttrans.Start() \r\n\t\t\t\tfor element in joinable_elements:\r\n\t\t\t\t\tbbox = element.get_BoundingBox(view_ele)\r\n\t\t\t\t\tif bbox:\r\n\t\t\t\t\t\toutline_ele = Outline(bbox.Min, bbox.Max)\r\n\t\t\t\t\t\tfilter_inters = BoundingBoxIntersectsFilter(outline_ele)\r\n\t\t\t\t\t\tif view_ele:\r\n\t\t\t\t\t\t\tall_inter_ele = self.getIntersectingElementsToJoin(sel_cats, view_ele, filter_inters)\r\n\t\t\t\t\t\telse:\r\n\t\t\t\t\t\t\tprogressForm._txtBlock2.Text = str(countIssues) + \" / \" + str(number_ele) + \" Elements Processed\"\r\n\t\t\t\t\t\t\tprogressForm._progressBar.PerformStep()\r\n\t\t\t\t\t\t\tprogressForm.Refresh()\r\n\t\t\t\t\t\t\tApplication.DoEvents()\r\n\t\t\t\t\t\t\tif progressForm.interrupt == True:\r\n\t\t\t\t\t\t\t\tbreak\r\n\t\t\t\t\t\t\tcountIssues+= 1\r\n\t\t\t\t\t\t\tall_inter_ele = self.getIntersectingSelectionToJoin(sel_cats, filter_inters, joinable_elements)\r\n\t\t\t\t\t\tif len(all_inter_ele) > 0:\r\n\t\t\t\t\t\t\tfor inter_ele in all_inter_ele:\r\n\t\t\t\t\t\t\t\tcontinue_processing = True\r\n\t\t\t\t\t\t\t\t#If elements already joined in previous iteration\r\n\t\t\t\t\t\t\t\tif element.Id == inter_ele.Id:\r\n\t\t\t\t\t\t\t\t\tcontinue_processing = False\r\n\t\t\t\t\t\t\t\telif joined_elements.ContainsKey(element.Id):\r\n\t\t\t\t\t\t\t\t\tif inter_ele.Id in joined_elements[element.Id]:\r\n\t\t\t\t\t\t\t\t\t\tcontinue_processing = False\r\n\t\t\t\t\t\t\t\ttry:\r\n\t\t\t\t\t\t\t\t\tareElementsJoined = JoinGeometryUtils.AreElementsJoined(doc, element, inter_ele)\r\n\t\t\t\t\t\t\t\t\tif continue_processing and not areElementsJoined:\r\n\t\t\t\t\t\t\t\t\t\tJoinGeometryUtils.JoinGeometry(doc, element, inter_ele)\r\n\t\t\t\t\t\t\t\t\t\tif joined_elements.ContainsKey(inter_ele.Id):\r\n\t\t\t\t\t\t\t\t\t\t\tjoined_elements[inter_ele.Id].Add(element.Id)\r\n\t\t\t\t\t\t\t\t\t\telse:\r\n\t\t\t\t\t\t\t\t\t\t\tjoined_elements.Add(inter_ele.Id, [element.Id])\r\n\t\t\t\t\t\t\t\t\t\t#Check join order and switch if needed\r\n\t\t\t\t\t\t\t\t\t\tself.checkOrderJoints(element, inter_ele, self.cat_priorities)\r\n\t\t\t\t\t\t\t\texcept Exception as exc:\r\n\t\t\t\t\t\t\t\t\tpass\r\n\t\t\t\tif view_ele:\r\n\t\t\t\t\ttrans.Commit()\r\n\t\t\t\telse:\r\n\t\t\t\t\tif progressForm.interrupt == True:\r\n\t\t\t\t\t\ttrans.RollBack()\r\n\t\t\t\t\t\tprogressForm.Close()\r\n\t\t\t\t\t\tAutodesk.Revit.UI.TaskDialog.Show(\"Process Cancelled\",\"The process has been interrupted. Any change done during the process was undo.\")\r\n\t\t\t\t\t\tobjForm.Show()\r\n\t\t\t\t\telse:\r\n\t\t\t\t\t\ttrans.Commit()\r\n\t\t\t\t\t\tprogressForm.Close()\r\n\t\t\t\t\t\tobjForm.Show()\r\n\t\texcept Exception as exc:\r\n\t\t\tAutodesk.Revit.UI.TaskDialog.Show(\"Exception Joining Process\", str(exc) + \" - \" + str(sys.exc_info()[-1].tb_lineno))\r\n\t\t\t\r\n\tdef filteredElementsCategories(self, sel_ids, categories_sel):\r\n\t\tids_categories = [ElementId(x) for x in categories_sel]\r\n\t\tif ElementId(BuiltInCategory.OST_Walls) in ids_categories:\r\n\t\t\tids_categories.Add(ElementId(BuiltInCategory.OST_StackedWalls))\r\n\t\tfiltered_selection = List[Element]()\r\n\t\tfor id in sel_ids:\r\n\t\t\tele = new_doc.GetElement(id)\r\n\t\t\tif ele.Category:\r\n\t\t\t\tif ele.Category.Id in ids_categories:\r\n\t\t\t\t\tfiltered_selection.Add(ele)\r\n\t\treturn filtered_selection\r\n\t\r\n\tdef windowNothingSelected(self):\r\n\t\tobjForm.Hide()\r\n\t\tAutodesk.Revit.UI.TaskDialog.Show(\"Join In Views\",\"Please, select at least 2 elements of the checked categories to join.\")\r\n\t\tobjForm.Show()\r\n\r\n\tdef getAllElementsToJoin(self, categories, id_view):\r\n\t\tfiltered_elements = List[Element]()\r\n\t\tfor category in categories:\r\n\t\t\tif category == BuiltInCategory.OST_Walls:\r\n\t\t\t\tfiltered_elements.AddRange(FilteredElementCollector(new_doc, id_view).OfCategory(BuiltInCategory.OST_StackedWalls))\r\n\t\t\tfiltered_elements.AddRange(FilteredElementCollector(new_doc, id_view).OfCategory(category))\r\n\t\treturn filtered_elements\r\n\t\r\n\tdef getIntersectingElementsToJoin(self, categories, view, inters_filter):\r\n\t\tfiltered_elements = List[Element]()\r\n\t\tfor category in categories:\r\n\t\t\tif category == BuiltInCategory.OST_Walls:\r\n\t\t\t\tfiltered_elements.AddRange(FilteredElementCollector(new_doc, view.Id).OfCategory(BuiltInCategory.OST_StackedWalls).WherePasses(inters_filter))\r\n\t\t\tfiltered_elements.AddRange(FilteredElementCollector(new_doc, view.Id).OfCategory(category).WherePasses(inters_filter))\r\n\t\treturn filtered_elements\r\n\t\r\n\tdef getIntersectingSelectionToJoin(self, categories, inters_filter, list_eles):\r\n\t\tlist_ids = List[ElementId]()\r\n\t\tfor ele in list_eles:\r\n\t\t\tlist_ids.Add(ele.Id)\r\n\t\tfiltered_elements = List[Element]()\r\n\t\tfor category in categories:\r\n\t\t\tif category == BuiltInCategory.OST_Walls:\r\n\t\t\t\tfiltered_elements.AddRange(FilteredElementCollector(new_doc, list_ids).OfCategory(BuiltInCategory.OST_StackedWalls).WherePasses(inters_filter))\r\n\t\t\tfiltered_elements.AddRange(FilteredElementCollector(new_doc, list_ids).OfCategory(category).WherePasses(inters_filter))\r\n\t\treturn filtered_elements\r\n\t\t\r\n\tdef checkOrderJoints(self, ele1, ele2, categories):\r\n\t\tcat_1 = ele1.Category.Id\r\n\t\tif cat_1 == ElementId(BuiltInCategory.OST_StackedWalls):\r\n\t\t\tcat_1 = ElementId(BuiltInCategory.OST_Walls)\r\n\t\tcat_2 = ele2.Category.Id\r\n\t\tif cat_2 == ElementId(BuiltInCategory.OST_StackedWalls):\r\n\t\t\tcat_2 = ElementId(BuiltInCategory.OST_Walls)\r\n\t\tpriority_1 = 0\r\n\t\tpriority_2 = 0\r\n\t\tfor index, bic_cat in enumerate(categories):\r\n\t\t\tcat = ElementId(bic_cat)\r\n\t\t\tif cat == cat_1:\r\n\t\t\t\tpriority_1 = index\r\n\t\t\tif cat == cat_2:\r\n\t\t\t\tpriority_2 = index\r\n\t\t\t\t\r\n\t\tif priority_1 != priority_2:\r\n\t\t\tif (JoinGeometryUtils.IsCuttingElementInJoin(new_doc, ele1, ele2)) == (priority_1 < priority_2):\r\n\t\t\t\treturn False\r\n\t\t\telse:\r\n\t\t\t\t#Reorder joint\r\n\t\t\t\tJoinGeometryUtils.SwitchJoinOrder(new_doc, ele1, ele2)\r\n\t\t\t\treturn True\r\n\t\treturn False\r\n\t\t\r\n\tdef GetName(self):\r\n\t\treturn \"Join Elements\"\r\n\r\nclass FormWithProgresBar(Form):\r\n\tdef __init__(self):\r\n\t\tself.Font = Font(\"Arial\", 15, FontStyle.Regular, GraphicsUnit.Pixel)\r\n\t\tself.interrupt = False\r\n\t\tself.numberItems = 5\r\n\t\tself.TopMost = True\r\n\t\tself.Closing += self.closingevent\r\n\t\tself.InitializeComponent()\r\n\t\t\r\n\tdef InitializeComponent(self):\r\n\t\tself._spr_top     = System.Windows.Forms.Label()\r\n\t\tself._progressBar = System.Windows.Forms.ProgressBar()\r\n\t\tself._button1 = System.Windows.Forms.Button()\r\n\t\tself._txtBlock2 = System.Windows.Forms.Label()\r\n\t\tself.SuspendLayout()\r\n\t\t# \r\n\t\t# Separator Top\r\n\t\t# \r\n\t\tself._spr_top.Anchor     = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right\r\n\t\tself._spr_top.Location   = System.Drawing.Point(0, 0)\r\n\t\tself._spr_top.Name       = \"spr_top\"\r\n\t\tself._spr_top.Size       = System.Drawing.Size(2000, 2)\r\n\t\tself._spr_top.BackColor  = Color.FromArgb(82, 53, 239)\r\n\t\t# \r\n\t\t# TextBlock2\r\n\t\t# \r\n\t\tself._txtBlock2.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left\r\n\t\tself._txtBlock2.TextAlign = ContentAlignment.MiddleCenter\r\n\t\tself._txtBlock2.Location = System.Drawing.Point(0, 5)\r\n\t\tself._txtBlock2.Name = \"txtBlock2\"\r\n\t\tself._txtBlock2.Size = System.Drawing.Size(250, 20)\r\n\t\tself._txtBlock2.TabIndex = 1\r\n\t\tself._txtBlock2.Text = \"0 / 0 Views Processed\"\r\n\t\t# \r\n\t\t# ProgressBar\r\n\t\t# \r\n\t\tself._progressBar.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left\r\n\t\tself._progressBar.Location = System.Drawing.Point(15, 30)\r\n\t\tself._progressBar.Name = \"progressBar\"\r\n\t\tself._progressBar.Size = System.Drawing.Size(220, 15)\r\n\t\tself._progressBar.Value = 1\r\n\t\tself._progressBar.TabIndex = 1\r\n\t\t# \r\n\t\t# button1\r\n\t\t# \r\n\t\tself._button1.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right\r\n\t\tself._button1.Location = System.Drawing.Point(14, 50)\r\n\t\tself._button1.Name = \"button1\"\r\n\t\tself._button1.Size = System.Drawing.Size(222, 20)\r\n\t\tself._button1.TabIndex = 2\r\n\t\tself._button1.Text = \"Interrupt / Cancel\"\r\n\t\tself._button1.UseVisualStyleBackColor = True\r\n\t\tself._button1.Click += self.Button1Click\r\n\t\t# \r\n\t\t# Form24\r\n\t\t# \r\n\t\tself.ClientSize = System.Drawing.Size(250, 85)\r\n\t\tself.MaximizeBox = 0\r\n\t\tself.MinimizeBox = 0\r\n\t\tself.CenterToScreen() \r\n\t\tself.FormBorderStyle = FormBorderStyle.FixedSingle\r\n\t\tself.Controls.Add(self._spr_top)\r\n\t\tself.Controls.Add(self._txtBlock2)\r\n\t\tself.Controls.Add(self._button1)\r\n\t\tself.Controls.Add(self._progressBar)\r\n\t\tself.Name = \"Joining Elements...\"\r\n\t\tself.Text = \"Joining Elements...\"\r\n\t\ticonFilename = 'C:\\\\NONICAPRO\\\\OtherFiles\\\\System\\\\Nonicafavicon.ICO'\r\n\t\tif not os.path.exists(iconFilename):\r\n\t\t\ticonFilename = 'C:\\\\NONICA\\\\OtherFiles\\\\System\\\\Nonicafavicon.ICO'\r\n\t\ticon = Icon(iconFilename)\r\n\t\tself.Icon = icon\r\n\t\tself.ResumeLayout(False)\r\n\tdef Button1Click(self, sender, e):\r\n\t\tself.interrupt = True\r\n\tdef closingevent(self, sender, e):\r\n\t\tself.interrupt = True\r\n\r\nclass Form_Joining(Form):\r\n\tdef __init__(self, names_cat, categories_to_join, ordered_view_names, ordered_view_ids, join_ev, names_categories_pri, categories_priority, ev_unsubscribe):\r\n\t\tself.Font = Font(\"Arial\", 15, FontStyle.Regular, GraphicsUnit.Pixel)\r\n\t\tself.doc_sub_eve = ev_unsubscribe\r\n\t\tself.selectionhistory = []\r\n\t\tself.selectionhistory2 = []\r\n\t\tself.cat_pri = categories_priority\r\n\t\tself.cat_nam = names_categories_pri\r\n\t\tself.ev_join = join_ev\r\n\t\tself._tableData = DataTable(\"Data\")\r\n\t\tself._tableData.Columns.Add(\"Key\", System.String)\r\n\t\tself._tableData.Columns.Add(\"Value\", System.Object)\r\n\t\t[self._tableData.Rows.Add(key_, value_ ) for key_, value_ in zip(names_cat, categories_to_join)]\r\n\t\tself._tableDataViews = DataTable(\"Data\")\r\n\t\tself._tableDataViews.Columns.Add(\"Key\", System.String)\r\n\t\tself._tableDataViews.Columns.Add(\"Value\", System.Object)\r\n\t\t[self._tableDataViews.Rows.Add(key_, value_ ) for key_, value_ in zip(ordered_view_names, ordered_view_ids)]\r\n\t\tself.InitializeComponent()\r\n\t\r\n\tdef InitializeComponent(self):\r\n\t\tself._spr_top     = System.Windows.Forms.Label()\r\n\t\tself.checkedListBox1 = System.Windows.Forms.CheckedListBox()\r\n\t\tself.label1 = Label()\r\n\t\tself.checkBox1 = CheckBox()\r\n\t\tself.checkedListBox2 = System.Windows.Forms.CheckedListBox()\r\n\t\tself.label2 = Label()\r\n\t\tself.button2 = Button()\r\n\t\tself.button1 = Button()\r\n\t\tself.toolTip1 = System.Windows.Forms.ToolTip()\r\n\t\tself.SuspendLayout()\r\n\t\t# \r\n\t\t# Separator Top\r\n\t\t# \r\n\t\tself._spr_top.Anchor     = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right\r\n\t\tself._spr_top.Location   = System.Drawing.Point(0, 0)\r\n\t\tself._spr_top.Name       = \"spr_top\"\r\n\t\tself._spr_top.Size       = System.Drawing.Size(2000, 2)\r\n\t\tself._spr_top.BackColor  = Color.FromArgb(82, 53, 239)\r\n\t\t# \r\n\t\t# label1\r\n\t\t# \r\n\t\tself.label1.AutoSize = True\r\n\t\tself.label1.Location = Point(12, 9)\r\n\t\tself.label1.Name = \"label1\"\r\n\t\tself.label1.Size = Size(164, 20)\r\n\t\tself.label1.TabIndex = 1\r\n\t\tself.label1.Text = \"Views To Join Elements:\"\r\n\t\t# \r\n\t\t# checkedListBox1\r\n\t\t# \r\n\t\tself.checkedListBox1.Anchor = System.Windows.Forms.AnchorStyles.Top |  System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right | System.Windows.Forms.AnchorStyles.Bottom\r\n\t\tself.checkedListBox1.FormattingEnabled = True\r\n\t\tself.checkedListBox1.CheckOnClick = True\r\n\t\tself.checkedListBox1.Location = Point(12, 32)\r\n\t\tself.checkedListBox1.Name = \"checkedListBox2\"\r\n\t\tself.checkedListBox1.Size = Size(312, 203)\r\n\t\tself.checkedListBox1.TabIndex = 0\r\n\t\tself.checkedListBox1.DataSource = self._tableDataViews\r\n\t\tself.checkedListBox1.DisplayMember = \"Key\"\r\n\t\tself.checkedListBox1.SelectedIndexChanged += self.changeSelection\r\n\t\tself.checkedListBox1.HorizontalScrollbar = True\r\n\t\t# \r\n\t\t# checkBox1\r\n\t\t# \r\n\t\tself.checkBox1.Anchor =  System.Windows.Forms.AnchorStyles.Bottom |  System.Windows.Forms.AnchorStyles.Left\r\n\t\tself.checkBox1.AutoSize = True\r\n\t\tself.checkBox1.Location = Point(12, 233)\r\n\t\tself.checkBox1.Name = \"checkBox1\"\r\n\t\tself.checkBox1.Size = Size(239, 24)\r\n\t\tself.checkBox1.TabIndex = 2\r\n\t\tself.checkBox1.Text = \"Only Join Elements Selected in Revit.\"\r\n\t\tself.checkBox1.UseVisualStyleBackColor = True\r\n\t\tself.checkBox1.CheckedChanged += self.ClickedOnlySelection\r\n\t\tself.toolTip1.SetToolTip(self.checkBox1, \"Check this option to only join the elements you select in Revit.\")\r\n\t\t# \r\n\t\t# checkedListBox2\r\n\t\t# \r\n\t\tself.checkedListBox2.Anchor = System.Windows.Forms.AnchorStyles.Bottom |  System.Windows.Forms.AnchorStyles.Left |  System.Windows.Forms.AnchorStyles.Right\r\n\t\tself.checkedListBox2.FormattingEnabled = True\r\n\t\tself.checkedListBox2.CheckOnClick = True\r\n\t\tself.checkedListBox2.Location = Point(12, 281)\r\n\t\tself.checkedListBox2.Name = \"checkedListBox2\"\r\n\t\tself.checkedListBox2.Size = Size(312, 180)\r\n\t\tself.checkedListBox2.TabIndex = 3\r\n\t\tself.checkedListBox2.DataSource = self._tableData\r\n\t\tself.checkedListBox2.DisplayMember = \"Key\"\r\n\t\tself.checkedListBox2.SelectedIndexChanged += self.changeSelection2\r\n\t\t# \r\n\t\t# label2\r\n\t\t# \r\n\t\tself.label2.Anchor = System.Windows.Forms.AnchorStyles.Bottom |  System.Windows.Forms.AnchorStyles.Left\r\n\t\tself.label2.AutoSize = True\r\n\t\tself.label2.Location = Point(12, 258)\r\n\t\tself.label2.Name = \"label2\"\r\n\t\tself.label2.Size = Size(133, 20)\r\n\t\tself.label2.TabIndex = 4\r\n\t\tself.label2.Text = \"Categories To Join:\"\r\n\t\t# \r\n\t\t# button2\r\n\t\t# \r\n\t\tself.button2.Anchor = System.Windows.Forms.AnchorStyles.Bottom |  System.Windows.Forms.AnchorStyles.Left |  System.Windows.Forms.AnchorStyles.Right\r\n\t\tself.button2.Location = Point(12, 462)\r\n\t\tself.button2.Name = \"button2\"\r\n\t\tself.button2.Size = Size(272, 29)\r\n\t\tself.button2.TabIndex = 6\r\n\t\tself.button2.Text = \"Join Elements!\"\r\n\t\tself.button2.UseVisualStyleBackColor = True\r\n\t\tself.button2.Click += self.JoinElements\r\n\t\t# \r\n\t\t# button1\r\n\t\t# \r\n\t\tself.button1.Anchor = System.Windows.Forms.AnchorStyles.Bottom |  System.Windows.Forms.AnchorStyles.Right\r\n\t\tself.button1.Location = Point(290, 462)\r\n\t\tself.button1.Name = \"button1\"\r\n\t\tself.button1.Size = Size(34, 29)\r\n\t\tself.button1.TabIndex = 7\r\n\t\tself.button1.Text = \"↑ ↓\"\r\n\t\tself.button1.UseVisualStyleBackColor = True\r\n\t\tself.button1.Click += self.openPriorities\r\n\t\tself.toolTip1.SetToolTip(self.button1, \"Set up the Joining Order of which category should cut the others.\")\r\n\t\t# \r\n\t\t# Form24\r\n\t\t# \r\n\t\tself.Load += self.Preselection\r\n\t\tself.TopMost = True\r\n\t\tself.ShowInTaskbar = False\r\n\t\tself.ClientSize = System.Drawing.Size(334, 505)\r\n\t\tself.MaximizeBox = 0\r\n\t\tself.MinimizeBox = 0\r\n\t\tself.CenterToScreen()\r\n\t\tself.FormBorderStyle = FormBorderStyle.Sizable\r\n\t\tself.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Show\r\n\t\tself.Controls.Add(self._spr_top)\r\n\t\tself.Controls.Add(self.button1)\r\n\t\tself.Controls.Add(self.button2)\r\n\t\tself.Controls.Add(self.label2)\r\n\t\tself.Controls.Add(self.checkedListBox2)\r\n\t\tself.Controls.Add(self.checkBox1)\r\n\t\tself.Controls.Add(self.label1)\r\n\t\tself.Controls.Add(self.checkedListBox1)\r\n\t\tself.ShowInTaskbar = True\r\n\t\tself.MaximizeBox = True\r\n\t\tself.MinimizeBox = True   \r\n\t\tself.Closing += self.closingEvent\t\t\r\n\t\tself.Name = \"Join In Views\"\r\n\t\tself.Text = \"Join In Views\"\r\n\t\ticonFilename = 'C:\\\\NONICAPRO\\\\OtherFiles\\\\System\\\\Nonicafavicon.ICO'\r\n\t\tif not os.path.exists(iconFilename):\r\n\t\t\ticonFilename = 'C:\\\\NONICA\\\\OtherFiles\\\\System\\\\Nonicafavicon.ICO'\r\n\t\ticon = Icon(iconFilename)\r\n\t\tself.Icon = icon\r\n\t\tself.ResumeLayout(False)\r\n\t\t\r\n\tdef closingEvent(self, sender, e):\r\n\t\tisActive = 0\r\n\t\tself.doc_sub_eve.Raise()\r\n\t\t\r\n\tdef JoinElements(self, sender, e):\r\n\t\tif len(self.checkedListBox2.CheckedItems) == 0:\r\n\t\t\tself.Hide()\r\n\t\t\tAutodesk.Revit.UI.TaskDialog.Show(\"Join In Views\",\"Please, select one category to join at least.\")\r\n\t\t\tself.Show()\r\n\t\tif len(self.checkedListBox1.CheckedItems) == 0 and self.checkBox1.Checked == False:\r\n\t\t\tself.Hide()\r\n\t\t\tAutodesk.Revit.UI.TaskDialog.Show(\"Join In Views\",\"Please, select one view to join at least.\")\r\n\t\t\tself.Show()\r\n\t\telse:\r\n\t\t\tself.ev_join.Raise()\r\n\t\r\n\tdef openPriorities(self, sender, e):\r\n\t\tnames, built_cat = extractListsPriorities()\r\n\t\tif len(names) == 0:\r\n\t\t\tpriorityForm = Form_Order(self.cat_nam, self.cat_pri, self.cat_nam, self.cat_pri)\r\n\t\telse:\r\n\t\t\tpriorityForm = Form_Order(names, built_cat, self.cat_nam, self.cat_pri)\r\n\t\tpriorityForm.Show()\t\t\r\n\t\r\n\tdef ClickedOnlySelection(self, sender, e):\r\n\t\tif sender.Checked == True:\r\n\t\t\tself.checkedListBox1.Enabled = False\r\n\t\t\tself.checkedListBox1.BackColor = Color.LightGray\r\n\t\t\tself.checkedListBox1.SelectedIndex = -1\r\n\t\telse:\r\n\t\t\tself.checkedListBox1.Enabled = True\r\n\t\t\tself.checkedListBox1.BackColor = Color.White\r\n\t\r\n\tdef Preselection(self, sender, e):\r\n\t\tfor indx in range(0,6):\r\n\t\t\tself.checkedListBox2.SetItemCheckState(indx, CheckState.Checked);\r\n\t\t\t\r\n\tdef changeSelection(self, sender, e):\r\n\t\tactualcount = len(self.selectionhistory)\r\n\t\tif actualcount > 0:\r\n\t\t\tif Control.ModifierKeys == Keys.Shift:\r\n\t\t\t\tlastindex = self.selectionhistory[0]\r\n\t\t\t\tcurrentIndex = self.checkedListBox1.SelectedIndex\r\n\t\t\t\tstep = 1\r\n\t\t\t\tif currentIndex < lastindex:\r\n\t\t\t\t\tstep = -1\r\n\t\t\t\tfor i in range(lastindex, currentIndex, step):\r\n\t\t\t\t\tif i != lastindex:\r\n\t\t\t\t\t\tif self.checkedListBox1.GetItemCheckState(i) == CheckState.Checked:\r\n\t\t\t\t\t\t\tself.checkedListBox1.SetItemCheckState(i, CheckState.Unchecked);\r\n\t\t\t\t\t\telse:\r\n\t\t\t\t\t\t\tself.checkedListBox1.SetItemCheckState(i, CheckState.Checked);\r\n\t\t\tself.selectionhistory.Clear()\r\n\t\t\tself.selectionhistory.Add(self.checkedListBox1.SelectedIndex) \r\n\t\telse:\r\n\t\t\tself.selectionhistory.Clear()\r\n\t\t\tself.selectionhistory.Add(self.checkedListBox1.SelectedIndex) \r\n\r\n\tdef changeSelection2(self, sender, e):\r\n\t\tactualcount = len(self.selectionhistory2)\r\n\t\tif actualcount > 0:\r\n\t\t\tif Control.ModifierKeys == Keys.Shift:\r\n\t\t\t\tlastindex = self.selectionhistory2[0]\r\n\t\t\t\tcurrentIndex = self.checkedListBox2.SelectedIndex\r\n\t\t\t\tstep = 1\r\n\t\t\t\tif currentIndex < lastindex:\r\n\t\t\t\t\tstep = -1\r\n\t\t\t\tfor i in range(lastindex, currentIndex, step):\r\n\t\t\t\t\tif i != lastindex:\r\n\t\t\t\t\t\tif self.checkedListBox2.GetItemCheckState(i) == CheckState.Checked:\r\n\t\t\t\t\t\t\tself.checkedListBox2.SetItemCheckState(i, CheckState.Unchecked);\r\n\t\t\t\t\t\telse:\r\n\t\t\t\t\t\t\tself.checkedListBox2.SetItemCheckState(i, CheckState.Checked);\r\n\t\t\tself.selectionhistory2.Clear()\r\n\t\t\tself.selectionhistory2.Add(self.checkedListBox2.SelectedIndex) \r\n\t\telse:\r\n\t\t\tself.selectionhistory2.Clear()\r\n\t\t\tself.selectionhistory2.Add(self.checkedListBox1.SelectedIndex) \r\n\t\t\t\r\nclass Form_Order(Form):\r\n\tdef __init__(self, cate_names, cate_priority, def_names, def_values):\r\n\t\tself.Font = Font(\"Arial\", 15, FontStyle.Regular, GraphicsUnit.Pixel)\r\n\t\tself.cat_nam = cate_names\r\n\t\tself.cat_pri = cate_priority\r\n\t\tself.def_cat_nam = def_names\r\n\t\tself.def_cat_pri = def_values\r\n\t\tself._tableData = DataTable(\"Data\")\r\n\t\tself._tableData.Columns.Add(\"Key\", System.String)\r\n\t\tself._tableData.Columns.Add(\"Value\", System.Object)\r\n\t\t[self._tableData.Rows.Add(key_, value_ ) for key_, value_ in zip(self.cat_nam, self.cat_pri)]\r\n\t\tself.InitializeComponent()\r\n\t\r\n\tdef InitializeComponent(self):\r\n\t\tself._spr_top     = System.Windows.Forms.Label()\r\n\t\tself.listBox1 = System.Windows.Forms.ListBox()\r\n\t\tself.label1 = Label()\r\n\t\tself.label2 = Label()\r\n\t\tself.label3 = Label()\r\n\t\tself.button1 = Button()\r\n\t\tself.button2 = Button()\r\n\t\tself.button3 = Button()\r\n\t\tself.SuspendLayout()\r\n\t\t# \r\n\t\t# Separator Top\r\n\t\t# \r\n\t\tself._spr_top.Anchor     = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right\r\n\t\tself._spr_top.Location   = System.Drawing.Point(0, 0)\r\n\t\tself._spr_top.Name       = \"spr_top\"\r\n\t\tself._spr_top.Size       = System.Drawing.Size(2000, 2)\r\n\t\tself._spr_top.BackColor  = Color.FromArgb(82, 53, 239)\r\n\t\t# \r\n\t\t# label1\r\n\t\t# \r\n\t\tself.label1.AutoSize = True\r\n\t\tself.label1.Location = Point(12, 9)\r\n\t\tself.label1.Name = \"label1\"\r\n\t\tself.label1.Size = Size(164, 20)\r\n\t\tself.label1.TabIndex = 0\r\n\t\tself.label1.Text = \"Joining Order:\"\r\n\t\t# \r\n\t\t# label2\r\n\t\t# \r\n\t\tself.label2.AutoSize = True\r\n\t\tself.label2.Location = Point(12, 34)\r\n\t\tself.label2.Name = \"label2\"\r\n\t\tself.label2.Size = Size(164, 20)\r\n\t\tself.label2.TabIndex = 1\r\n\t\tself.label2.Text = \"(Higher position, Higher cut priority).\"\r\n\t\t# \r\n\t\t# ListBox1\r\n\t\t# \r\n\t\tself.listBox1.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right | System.Windows.Forms.AnchorStyles.Bottom\r\n\t\tself.listBox1.FormattingEnabled = True\r\n\t\tself.listBox1.Location = Point(12, 59)\r\n\t\tself.listBox1.Name = \"ListBox1\"\r\n\t\tself.listBox1.Size = Size(270, 150)\r\n\t\tself.listBox1.TabIndex = 2\r\n\t\tself.listBox1.DataSource = self._tableData\r\n\t\tself.listBox1.DisplayMember = \"Key\"\r\n\t\tself.listBox1.HorizontalScrollbar = True\r\n\t\t# \r\n\t\t# label3\r\n\t\t# \r\n\t\tself.label3.AutoSize = True\r\n\t\tself.label3.Location = Point(12, 205)\r\n\t\tself.label3.Name = \"label3\"\r\n\t\tself.label3.Size = Size(164, 20)\r\n\t\tself.label3.TabIndex = 1\r\n\t\tself.label3.Text = \"This configuration is Auto-Saved.\"\r\n\t\t# \r\n\t\t# button1 Default\r\n\t\t# \r\n\t\tself.button1.Anchor = System.Windows.Forms.AnchorStyles.Bottom |  System.Windows.Forms.AnchorStyles.Right\r\n\t\tself.button1.Location = Point(12, 230)\r\n\t\tself.button1.Name = \"button1\"\r\n\t\tself.button1.Size = Size(90, 29)\r\n\t\tself.button1.TabIndex = 3\r\n\t\tself.button1.Text = \"Default\"\r\n\t\tself.button1.UseVisualStyleBackColor = True\r\n\t\tself.button1.Click += self.defaultSettings\r\n\t\t# \r\n\t\t# button2 Move Down\r\n\t\t# \r\n\t\tself.button2.Anchor = System.Windows.Forms.AnchorStyles.Bottom |  System.Windows.Forms.AnchorStyles.Right\r\n\t\tself.button2.Location = Point(102, 230)\r\n\t\tself.button2.Name = \"button1\"\r\n\t\tself.button2.Size = Size(90, 29)\r\n\t\tself.button2.TabIndex = 3\r\n\t\tself.button2.Text = \"↓ Down\"\r\n\t\tself.button2.UseVisualStyleBackColor = True\r\n\t\tself.button2.Click += self.moveDown\r\n\t\t# \r\n\t\t# button3 Move Up\r\n\t\t# \r\n\t\tself.button3.Anchor = System.Windows.Forms.AnchorStyles.Bottom |  System.Windows.Forms.AnchorStyles.Right\r\n\t\tself.button3.Location = Point(192, 230)\r\n\t\tself.button3.Name = \"button1\"\r\n\t\tself.button3.Size = Size(90, 29)\r\n\t\tself.button3.TabIndex = 3\r\n\t\tself.button3.Text = \"↑ Up\"\r\n\t\tself.button3.UseVisualStyleBackColor = True\r\n\t\tself.button3.Click += self.moveUp\r\n\t\t# \r\n\t\t# Form24\r\n\t\t# \r\n\t\tself.TopMost = True\r\n\t\tself.ShowInTaskbar = False\r\n\t\tself.ClientSize = System.Drawing.Size(294, 270)\r\n\t\tself.MaximizeBox = 0\r\n\t\tself.MinimizeBox = 0\r\n\t\tself.CenterToScreen()\r\n\t\tself.FormBorderStyle = FormBorderStyle.FixedSingle\r\n\t\tself.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Show\r\n\t\tself.Controls.Add(self._spr_top)\r\n\t\tself.Controls.Add(self.label1)\r\n\t\tself.Controls.Add(self.label2)\r\n\t\tself.Controls.Add(self.label3)\r\n\t\tself.Controls.Add(self.listBox1)\r\n\t\tself.Controls.Add(self.button1)\r\n\t\tself.Controls.Add(self.button2)\r\n\t\tself.Controls.Add(self.button3)\r\n\t\tself.ShowInTaskbar = True\r\n\t\tself.MaximizeBox = False\r\n\t\tself.MinimizeBox = False            \r\n\t\tself.Name = \"Joining Order\"\r\n\t\tself.Text = \"Joining Order\"\r\n\t\ticonFilename = 'C:\\\\NONICAPRO\\\\OtherFiles\\\\System\\\\Nonicafavicon.ICO'\r\n\t\tif not os.path.exists(iconFilename):\r\n\t\t\ticonFilename = 'C:\\\\NONICA\\\\OtherFiles\\\\System\\\\Nonicafavicon.ICO'\r\n\t\ticon = Icon(iconFilename)\r\n\t\tself.Icon = icon\r\n\t\tself.ResumeLayout(False)\r\n\t\r\n\tdef moveDown(self, sender, e):\r\n\t\tnum_items = len(self.listBox1.Items)\r\n\t\tsel_indx = self.listBox1.SelectedIndex\r\n\t\tif sel_indx < (num_items - 1):\r\n\t\t\tselected = self._tableData.Rows[sel_indx]\r\n\t\t\tkey_sel = selected['Key']\r\n\t\t\tval_sel = selected['Value']\r\n\t\t\tdr = self._tableData.NewRow()\r\n\t\t\tdr['Key'] = key_sel\r\n\t\t\tdr['Value'] = val_sel\r\n\t\t\tself._tableData.Rows.RemoveAt(sel_indx)\r\n\t\t\tself._tableData.Rows.InsertAt(dr, sel_indx + 1)\r\n\t\t\tself.listBox1.SetSelected(sel_indx + 1, True)\r\n\t\t\tself.saveToFile()\r\n\t\t\t\r\n\tdef moveUp(self, sender, e):\r\n\t\tsel_indx = self.listBox1.SelectedIndex\r\n\t\tif sel_indx > 0:\r\n\t\t\tselected = self._tableData.Rows[sel_indx]\r\n\t\t\tkey_sel = selected['Key']\r\n\t\t\tval_sel = selected['Value']\r\n\t\t\tdr = self._tableData.NewRow()\r\n\t\t\tdr['Key'] = key_sel\r\n\t\t\tdr['Value'] = val_sel\r\n\t\t\tself._tableData.Rows.RemoveAt(sel_indx)\r\n\t\t\tself._tableData.Rows.InsertAt(dr, sel_indx - 1)\r\n\t\t\tself.listBox1.SetSelected(sel_indx - 1, True)\r\n\t\t\tself.saveToFile()\r\n\t\r\n\tdef defaultSettings(self, sender, e):\r\n\t\tself._tableData = DataTable(\"Data\")\r\n\t\tself._tableData.Columns.Add(\"Key\", System.String)\r\n\t\tself._tableData.Columns.Add(\"Value\", System.Object)\r\n\t\t[self._tableData.Rows.Add(key_, value_ ) for key_, value_ in zip(self.def_cat_nam, self.def_cat_pri)]\r\n\t\tself.listBox1.DataSource = self._tableData\r\n\t\tself.saveToFile()\r\n\t\t\r\n\tdef saveToFile(self):\r\n\t\ttry:\r\n\t\t\twith open(dir_path + \"/\" + \"settingsJoinElementsNonica.txt\",\"w\") as file:\r\n\t\t\t\tfor rw in self._tableData.Rows:\r\n\t\t\t\t\tfile.write(str(rw['Value'])+\"\\n\")\r\n\t\t\t\t\t#file.write(str(int(rw['Value']))+\"\\n\")\r\n\t\texcept Exception as e:\r\n\t\t\tpass\r\n\t\r\ndef getDocumentsFolder():\r\n    dll = ctypes.windll.shell32\r\n    buf = ctypes.create_unicode_buffer(MAX_PATH + 1)\r\n    if dll.SHGetSpecialFolderPathW(None, buf, 0x0005, False):\r\n        return buf.value\r\n    else:\r\n        return 0   \r\n\t        \r\ndef loadFromFile():\r\n\t#Default value\r\n\tcategories = []\r\n\ttry:\r\n\t\twith open(dir_path + \"/\" + \"settingsJoinElementsNonica.txt\",\"r\") as file:\r\n\t\t\tall_lines = file.readlines()\r\n\t\t\tfor line_txt in all_lines:\r\n\t\t\t\tcategories.Add(line_txt.strip())\r\n\t\treturn categories\r\n\texcept Exception as e:\r\n\t\treturn []\r\n\r\ndef extractListsPriorities():\r\n\tlist_pri = loadFromFile()\r\n\tif len(list_pri) != 0:\r\n\t\tnames = []\r\n\t\tbuiltin = []\r\n\t\tfor pri in list_pri:\r\n\t\t\tbuiltin.Add(getattr(BuiltInCategory, pri))\r\n\t\t\tnames.Add(dict_cat[pri])\r\n\t\treturn names, builtin\r\n\telse:\r\n\t\treturn [],[]\r\n\r\ndef OnViewActivated(sender, e):\r\n\tnew_docView = e.CurrentActiveView.Document\r\n\tif new_docView:\r\n\t\tnew_uiapp = new_docView.Application\r\n\t\tif isActive == 1:\r\n\t\t\tif objForm:\r\n\t\t\t\tif not new_docView.Equals(doc):\r\n\t\t\t\t\tobjForm.Close()\r\n\t\t\t\telse:\r\n\t\t\t\t\treturn\r\n\r\ndef OnFailuresProcessing(sender, e):\r\n\ttry:\r\n\t\ta = e.GetFailuresAccessor()\r\n\t\tfailures = a.GetFailureMessages()\r\n\t\tfor f in failures:\r\n\t\t\ttry:\r\n\t\t\t\tfailID = f.GetFailureDefinitionId()\r\n\t\t\t\tif failID == BuiltInFailures.JoinElementsFailures.JoiningDisjointWarn or failID == BuiltInFailures.JoinElementsFailures.JoiningDisjoint or str(failID.Guid) == \"1b9dacf3-db22-45d5-b071-42516278ffb1\" or failID == BuiltInFailures.CutFailures.CannotCutJoinedElement:\r\n\t\t\t\t\ta.ResolveFailures(failures)\r\n\t\t\t\t\te.SetProcessingResult(FailureProcessingResult.ProceedWithCommit)\r\n\t\t\texcept:\r\n\t\t\t\tpass\r\n\t\treturn e.SetProcessingResult(FailureProcessingResult.Continue)\r\n\texcept Exception as exc:\r\n\t\tpass\r\n\r\n\r\nuiapp = DocumentManager.Instance.CurrentUIApplication.Application\r\nglobal doc\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\nuidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument\r\napp = doc.Application\r\nglobal dir_path\r\ndir_path = getDocumentsFolder()\r\n\r\n#Protect against change of document\r\nisActive = 1\r\nnew_sub = System.EventHandler[Autodesk.Revit.UI.Events.ViewActivatedEventArgs](OnViewActivated)\r\nDocumentManager.Instance.CurrentUIApplication.ViewActivated += new_sub\r\nevent_handler_doc = UnsubcribeDocChange()\r\next_event_doc = ExternalEvent.Create(event_handler_doc)\r\n\r\n#FailuresProcessing\r\nglobal failureProc\r\nfailureProc = System.EventHandler[Autodesk.Revit.DB.Events.FailuresProcessingEventArgs](OnFailuresProcessing)\r\n\r\n#Categories to join order\r\ncategories_priority = [\r\nBuiltInCategory.OST_StructuralFoundation,\r\nBuiltInCategory.OST_StructuralColumns,\r\nBuiltInCategory.OST_Columns,\r\nBuiltInCategory.OST_Walls,\r\nBuiltInCategory.OST_Floors,\r\nBuiltInCategory.OST_StructuralFraming,\r\nBuiltInCategory.OST_Ceilings,\r\nBuiltInCategory.OST_Roofs]\r\n\r\nnames_categories_pri = [\r\n\"↕ Structural Foundation\",\r\n\"↕ Structural Columns\",\r\n\"↕ Architectural Columns\",\r\n\"↕ Walls\",\r\n\"↕ Floors\",\r\n\"↕ Structural Framing\",\r\n\"↕ Ceilings\",\r\n\"↕ Roofs\"]\r\n\r\nglobal dict_cat\r\ndict_cat={}\r\nfor cat_name, cat_built in zip(names_categories_pri, categories_priority):\r\n\tdict_cat[cat_built.ToString()] = cat_name\r\n\r\n#Categories to select\r\ncategories_to_join = [\r\nBuiltInCategory.OST_Columns,\r\nBuiltInCategory.OST_Floors,\r\nBuiltInCategory.OST_StructuralColumns,\r\nBuiltInCategory.OST_StructuralFoundation,\r\nBuiltInCategory.OST_StructuralFraming,\r\nBuiltInCategory.OST_Walls,\r\nBuiltInCategory.OST_Ceilings,\r\nBuiltInCategory.OST_Roofs]\r\n\r\nnames_categories = [\r\n\"Architectural Columns\",\r\n\"Floors\",\r\n\"Structural Columns\",\r\n\"Structural Foundation\",\r\n\"Structural Framing\",\r\n\"Walls\",\r\n\"Ceilings\",\r\n\"Roofs\"]\r\n\r\n#Get all views and order them\r\ncollector = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Views).ToElements()\r\nview_ids = []\r\nview_names = []\r\nfor view in collector:\r\n\tif view and not view.IsTemplate and view.ViewType != ViewType.Legend and view.ViewType != ViewType.Rendering and view.ViewType != ViewType.DraftingView:\r\n\t\tview_names.Add(view.Title)\r\n\t\tview_ids.Add(view.Id)\r\nzip_names_ids = zip(view_names, view_ids)\r\nzip_ordered = sorted(zip_names_ids, key = lambda x: x[0])\r\nordered_view_names = [x[0] for x in zip_ordered]\r\nordered_view_ids = [x[1] for x in zip_ordered]\r\n\r\nevent_handler_joinEle = joinElements(categories_priority)\r\next_event_join = ExternalEvent.Create(event_handler_joinEle)\r\n\r\nobjForm = Form_Joining(names_categories, categories_to_join, ordered_view_names, ordered_view_ids, ext_event_join, names_categories_pri, categories_priority, ext_event_doc)\r\nobjForm.Show()\r\n\r\nOUT = 0\r\n\r\n\"\"\"\r\nLicense Agreement\r\nFor the use of this script\r\nThis License Agreement (this “Agreement” of this “License Agreement”) is made and effective as of the current date (the “Commencement Date”) by and between Nonica by Estudio Alonso Candau SLP a company organized and existing in Spain with a registered address at Avd.Chafarinas 16 Puerto Rey Vera, Almeria (“Licensor”) and yourself (“Licensee”).\r\nWHEREAS:\r\n1.    Licensee wishes to obtain access and use this script (hereinafter, the “Asset”), and\r\n2.    Licensor is willing to grant to the Licensee a non-exclusive, non-transferable License to use the Asset for the term and specific purpose set forth in this Agreement,\r\nNOW, THEREFORE, your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or use this script.\r\n1. Definitions\r\n1.1 “Agreement” means this License Agreement including the attached Schedule.\r\n1.2 “Confidential Information” means information that:\r\na. is by its nature confidential;\r\nb. is designated in writing by Licensor as confidential;\r\nc. the Licensee knows or reasonably ought to know is confidential;\r\nd. Information comprised in or relating to any Intellectual Property Rights of Licensor.\r\n1.3 “Asset” means the Asset provided by Licensor as specified in Item 6 of the Schedule in the form as stated in Item 7 of the Schedule.\r\n1.4 “Intellectual Property Rights” means all rights in and to any copyright, trademark, trading name, design, patent, know how (trade secrets) and all other rights resulting from intellectual activity in the industrial, scientific, literary or artistic field and any application or right to apply for registration of any of these rights and any right to protect or enforce any of these rights, as further specified in clause 5.\r\n1.5 “Party” means a person or business entity who has executed this Agreement; details of the Parties are specified in Item 2 of the Schedule.\r\n1.6 “Term” means the term of this Agreement commencing on the Commencement Date as specified in Item 4 of the Schedule and expiring on the Expiry Date specified in Item 5 of the Schedule.\r\n2. License Grant\r\n2.1 Licensor grants to the Licensee a non-exclusive, non-transferable License for the Term to use the Asset for the specific purpose specified in this Agreement, subject to the terms and conditions set out in this Agreement.\r\n3. Charges\r\n3.1 In consideration of the Licensor providing the License under clause 2 of this License Agreement, the Licensee agrees to pay Licensor the amount of the License Charge as specified in Item 9 of the Schedule.\r\n4. Licensee’s Obligations\r\n4.1 The Licensee cannot use the Asset, for purposes other than as specified in this Agreement and in Item 8 of the Schedule.\r\n4.2 The Licensee may permit its employees to use the Asset for the purposes described in Item 8, provided that the Licensee takes all necessary steps and imposes the necessary conditions to ensure that all employees using the Asset do not commercialise or disclose the contents of it to any third person, or use it other than in accordance with the terms of this Agreement.\r\n4.3 The Licensee will not distribute, sell, License or sub-License, let, trade or expose for sale the Asset to a third party.\r\n4.4 No copies of the Asset are to be made other than as expressly approved by Licensor.\r\n4.5 No changes to the Asset or its content may be made by Licensee.\r\n4.6 The Licensee will provide technological and security measures to ensure that the Asset which the Licensee is responsible for is physically and electronically secure from unauthorised use or access.\r\n4.7 Licensee shall ensure that the Asset retains all Licensor copyright notices and other proprietary legends and all trademarks or service marks of Licensor.\r\n5. Intellectual Property Rights\r\n5.1 All Intellectual Property Rights over and in respect of the Asset are owned by Licensor. The Licensee does not acquire any rights of ownership in the Asset.\r\n6. Limitation of Liability\r\n6.1 The Licensee acknowledges and agrees that neither Licensor nor its board members, officers, employees or agents, will be liable for any loss or damage arising out of or resulting from Licensor’s provision of the Asset under this Agreement, or any use of the Asset by the Licensee or its employees; and Licensee hereby releases Licensor to the fullest extent from any such liability, loss, damage or claim.\r\n7. Confidentiality\r\n7.1 Neither Party may use, disclose or make available to any third party the other Party’s Confidential Information, unless such use or disclosure is done in accordance with the terms of this Agreement.\r\n7.2 Each Party must hold the other Party’s Confidential Information secure and in confidence, except to the extent that such Confidential Information:\r\na. is required to be disclosed according to the requirements of any law, judicial or legislative body or government agency; or\r\nb. was approved for release in writing by the other Party, but only to the extent of and subject to such conditions as may be imposed in such written authorisation.\r\n7.3 This clause 7 will survive termination of this Agreement.\r\n8. Disclaimers & Release\r\n8.1 To the extent permitted by law, Licensor will in no way be liable to the Licensee or any third party for any loss or damage, however caused (including through negligence) which may be directly or indirectly suffered in connection with any use of the Asset.\r\n8.2 The Asset is provided by Licensor on an “as is” basis.\r\n8.3 Licensor will not be held liable by the Licensee in any way, for any loss, damage or injury suffered by the Licensee or by any other person related to any use of the Asset or any part thereof.\r\n8.4 Notwithstanding anything contained in this Agreement, in no event shall Licensor be liable for any claims, damages or loss which may arise from the modification, combination, operation or use of the Asset with Licensee computer programs.\r\n8.5 Licensor does not warrant that the Asset will function in any environment.\r\n8.6 The Licensee acknowledges that: a. The Asset has not been prepared to meet any specific requirements of any party, including any requirements of Licensee; and b. it is therefore the responsibility of the Licensee to ensure that the Asset meets its own individual requirements.\r\n8.7 To the extent permitted by law, no express or implied warranty, term, condition or undertaking is given or assumed by Licensor, including any implied warranty of merchantability or fitness for a particular purpose.\r\n9. Indemnification\r\n9.1 The Licensee must indemnify, defend and hold harmless Licensor, its board members, officers, employees and agents from and against any and all claims (including third party claims), demands, actions, suits, expenses (including attorney’s fees) and damages (including indirect or consequential loss) resulting in any way from:\r\na. Licensee’s and Licensee’s employee’s use or reliance on the Asset,\r\nb. any breach of the terms of this License Agreement by the Licensee or any Licensee employee, and\r\nc. any other act of Licensee.\r\n9.2 This clause 9 will survive termination of this Agreement.\r\n10. Waiver\r\n10.1 Any failure or delay by either Party to exercise any right, power or privilege hereunder or to insist upon observance or performance by the other of the provisions of this License Agreement shall not operate or be construed as a waiver thereof.\r\n11. Governing Law\r\n11.1 This Agreement will be construed by and governed in accordance with the laws of Spain. The Parties submit to exclusive jurisdiction of the courts of Spain.\r\n12. Termination\r\n12.1 This Agreement and the License granted herein commences upon the Commencement Date and is granted for the Term, unless otherwise terminated by Licensor in the event of any of the following:\r\na. if the Licensee is in breach of any term of this License Agreement and has not corrected such breach to Licensor’s reasonable satisfaction within 7 days of Licensor’s notice of the same;\r\nb. if the Licensee becomes insolvent, or institutes (or there is instituted against it) proceedings in bankruptcy, insolvency, reorganization or dissolution, or makes an assignment for the benefit of creditors; or\r\nc. the Licensee is in breach of clause 5 or 7 of this Agreement.\r\n12.2 Termination under this clause shall not affect any other rights or remedies Licensor may have.\r\n14. Assignment\r\n14.1 Licensee shall not assign any rights of this License Agreement, without the prior written consent of Licensor.\r\n15. Notices\r\n15.1 All notices required under this Agreement shall be in writing and shall be deemed given (i) when delivered personally; (ii) five (5) days after mailing, when sent certified mail, return receipt requested and postage prepaid; or (iii) one (1) business day after dispatch, when sent via a commercial overnight carrier, fees prepaid. All notices given by either Party must be sent to the address of the other as first written above (unless otherwise changed by written notice).\r\n16. Counterparts\r\n16.1 This Agreement may be executed in any number of counterparts, each of which shall be deemed to be an original and all of which taken together shall constitute one instrument.\r\n17. Severability\r\n17.1 The Parties recognize the uncertainty of the law with respect to certain provisions of this Agreement and expressly stipulate that this Agreement will be construed in a manner that renders its provisions valid and enforceable to the maximum extent possible under applicable law. To the extent that any provisions of this Agreement are determined by a court of competent jurisdiction to be invalid or unenforceable, such provisions will be deleted from this Agreement or modified so as to make them enforceable and the validity and enforceability of the remainder of such provisions and of this Agreement will be unaffected.\r\n18. Entire Agreement\r\n18.1 This Agreement contains the entire agreement between the Parties and supersedes any previous understanding, commitments or agreements, oral or written. Further, this Agreement may not be modified, changed, or otherwise altered in any respect except by a written agreement signed by both Parties.\r\nIN WITNESS WHEREOF, this Agreement, including the attached Schedule, was signed by the Parties under the hands of their duly authorized representatives and made effective as of the current date.\r\nNonica by Estudio Alonso Candau SLP,\r\nSignature\r\n02/05/2021\r\nJaime Alonso Candau\r\nPlease contact hello@nonica.io with any further doubt/request.\r\nYour signatureby using and accessing this script.\r\nSigned by accepting these terms.\r\nCurrent date.\r\n\r\n\"\"\"",
      "VariableInputPorts": true,
      "Id": "72f3c5d829524eab992ecf59e6306288",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "00510581eb37439c8f5d9dd7639e00e9",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    }
  ],
  "Connectors": [],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.6.2.15705",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Join Elements",
        "Id": "72f3c5d829524eab992ecf59e6306288",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 278.16687837012608,
        "Y": 198.853993839431
      }
    ],
    "Annotations": [],
    "X": -698.99914928974681,
    "Y": -434.85318334905969,
    "Zoom": 3.118822334555428
  }
}